### ISSUE TITLE
error on starting scheduler task

### ISSUE THREAD

**Issue by baggyownz** [derhansen/tobserver#10]
Hello,

i get an error on starting the scheduler tasks and i did not how why.

The error message in scheduler module:
> Return value of "Derhansen\Tobserver\Command\CheckApiCommand::execute()" must be of the type int, "NULL" returned.

The error message in log module:

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: Return value of "Derhansen\Tobserver\Command\CheckApiCommand::execute()" must be of the type int, "NULL" returned. | 
> TypeError thrown in file /vendor/symfony/console/Command/Command.php in line 258. 
> Requested URL: https://www.domain.de/typo3/index.php?route=%%2Fmodule%%2Fsystem%%2FtxschedulerM1&token=--AnonymizedToken--&tx_scheduler[execute][]=3

Can somebody help me?

**Comment by derhansen** [comment]
Thanks for your report. It should work with the patch f198ea8 I just pushed.

**Comment by baggyownz** [comment]
Yes it worked.

Thank you for the quick help.
