### ISSUE TITLE
Do not find scheduler task

### ISSUE THREAD

**Issue by schrej-zz** [derhansen/tobserver#11]
Hi,
I configured tObserver but cannot configure a scheduler task as don't find any appropriate task in the list.
Typo3 V9.5.24
Thanks Joerg

**Comment by derhansen** [comment]
The scheduler task is a symfony command. Please setup the schedule as shown on the screenshots below

![image](https://user-images.githubusercontent.com/2629896/113749352-de98fc80-9709-11eb-95fa-ae9d1ad7691c.png)


![image](https://user-images.githubusercontent.com/2629896/113749389-e6f13780-9709-11eb-8b83-aeb4a2d24221.png)
