### ISSUE TITLE
Detect TYPO3 composer mode

### ISSUE THREAD

**Issue by derhansen** [derhansen/tobserver#7]

**Comment by runepiper** [comment]
Maybe this will help:

https://github.com/visuellverstehen/t3view/blob/master/Classes/Service/SystemInformationService.php#L104-L121

**Comment by derhansen** [comment]
You can use `Environment::isComposerMode()` since v9.5

**Comment by derhansen** [comment]
Added the new setting to tObserver 

![image](https://user-images.githubusercontent.com/2629896/74468871-dcd40000-4e9b-11ea-8afc-9a306c6d72f1.png)
